#!/usr/bin/env python3
"""Generate ARC message helper code from schema/messages.json.

This first generator intentionally supports only fixed-size scalar payloads.
That covers NETMGMT and RADIO now, and gives us a tested path before the larger
telemetry catalog exists.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schema" / "messages.json"
PY_TARGET = ROOT / "python" / "arc_protocol" / "messages_generated.py"

TYPE_INFO = {
    "u8": ("uint8_t", 1, False, "_u8"),
    "i8": ("int8_t", 1, True, "_i8"),
    "i16": ("int16_t", 2, True, "_i16"),
    "u16": ("uint16_t", 2, False, "_u16"),
    "i32": ("int32_t", 4, True, "_i32"),
    "u32": ("uint32_t", 4, False, "_u32"),
}


def parse_int(value: str | int) -> int:
    if isinstance(value, int):
        return value
    return int(value, 0)


def guard_for(target: str) -> str:
    name = Path(target).name.upper()
    return f"{name}_H"


def payload_size(message: dict) -> int:
    return sum(TYPE_INFO[field["type"]][1] for field in message.get("payload", []))


def generated_banner(comment: str) -> str:
    return (
        f"{comment} AUTO-GENERATED by tools/generate_messages.py.\n"
        f"{comment} Source schema: schema/messages.json\n"
        f"{comment} Edit the schema and regenerate; do not hand-edit this file.\n"
    )


def c_const(name: str, value: str | int) -> str:
    return f"#define {name:<32} 0x{parse_int(value):02X}"


def c_field_decl(field: dict) -> str:
    c_type = TYPE_INFO[field["type"]][0]
    return f"    {c_type} {field['name']};"


def c_encode_field(field: dict, offset: int) -> list[str]:
    name = field["name"]
    typ = field["type"]
    if typ == "u8":
        return [f"    out[{offset}] = msg->{name};"]
    if typ == "i8":
        return [f"    out[{offset}] = (uint8_t)msg->{name};"]
    if typ == "u16":
        return [
            f"    out[{offset}] = (uint8_t)((msg->{name} >> 8) & 0xFF);",
            f"    out[{offset + 1}] = (uint8_t)(msg->{name} & 0xFF);",
        ]
    if typ == "i16":
        return [
            f"    uint16_t {name}_wire = (uint16_t)msg->{name};",
            f"    out[{offset}] = (uint8_t)(({name}_wire >> 8) & 0xFF);",
            f"    out[{offset + 1}] = (uint8_t)({name}_wire & 0xFF);",
        ]
    if typ == "u32":
        return [
            f"    out[{offset}] = (uint8_t)((msg->{name} >> 24) & 0xFF);",
            f"    out[{offset + 1}] = (uint8_t)((msg->{name} >> 16) & 0xFF);",
            f"    out[{offset + 2}] = (uint8_t)((msg->{name} >> 8) & 0xFF);",
            f"    out[{offset + 3}] = (uint8_t)(msg->{name} & 0xFF);",
        ]
    if typ == "i32":
        return [
            f"    uint32_t {name}_wire = (uint32_t)msg->{name};",
            f"    out[{offset}] = (uint8_t)(({name}_wire >> 24) & 0xFF);",
            f"    out[{offset + 1}] = (uint8_t)(({name}_wire >> 16) & 0xFF);",
            f"    out[{offset + 2}] = (uint8_t)(({name}_wire >> 8) & 0xFF);",
            f"    out[{offset + 3}] = (uint8_t)({name}_wire & 0xFF);",
        ]
    raise ValueError(f"unsupported type {typ}")


def c_decode_field(field: dict, offset: int) -> list[str]:
    name = field["name"]
    typ = field["type"]
    if typ == "u8":
        return [f"    msg->{name} = in[{offset}];"]
    if typ == "i8":
        return [f"    msg->{name} = (int8_t)in[{offset}];"]
    if typ == "u16":
        return [
            f"    msg->{name} = ((uint16_t)in[{offset}] << 8) | (uint16_t)in[{offset + 1}];"
        ]
    if typ == "i16":
        return [
            f"    msg->{name} = (int16_t)(((uint16_t)in[{offset}] << 8) | (uint16_t)in[{offset + 1}]);"
        ]
    if typ == "u32":
        return [
            f"    msg->{name} =",
            f"        ((uint32_t)in[{offset}] << 24) |",
            f"        ((uint32_t)in[{offset + 1}] << 16) |",
            f"        ((uint32_t)in[{offset + 2}] << 8)  |",
            f"        ((uint32_t)in[{offset + 3}]);",
        ]
    if typ == "i32":
        return [
            f"    msg->{name} = (int32_t)(",
            f"        ((uint32_t)in[{offset}] << 24) |",
            f"        ((uint32_t)in[{offset + 1}] << 16) |",
            f"        ((uint32_t)in[{offset + 2}] << 8)  |",
            f"        ((uint32_t)in[{offset + 3}]));",
        ]
    raise ValueError(f"unsupported type {typ}")


def generate_c_header(family: dict) -> str:
    guard = guard_for(family["c_target"])
    prefix = family["c_type_prefix"]
    type_prefix = family["type_prefix"]
    out: list[str] = []
    out.append(generated_banner("//").rstrip())
    out.append("")
    out.append(f"#ifndef {guard}")
    out.append(f"#define {guard}")
    out.append("")
    out.append('#include "arc_protocol.h"')
    out.append("")
    out.append("#ifdef __cplusplus")
    out.append('extern "C" {')
    out.append("#endif")
    out.append("")

    if family["name"] != "NETMGMT":
        out.append("// Message types.")
        for msg in family["messages"]:
            out.append(c_const(f"{type_prefix}_{msg['name']}", msg["type"]))
        out.append("")

    for const in family.get("constants", []):
        out.append(c_const(f"{type_prefix}_{const['name']}", const["value"]))
    if family.get("constants"):
        out.append("")

    for msg in family["messages"]:
        fields = msg.get("payload", [])
        if not fields:
            continue
        struct_name = f"{prefix}_{msg['c_struct']}_t"
        size_name = f"{type_prefix}_{msg['name']}_PAYLOAD_SIZE"
        out.append(c_const(size_name, payload_size(msg)))
        out.append("")
        out.append("typedef struct {")
        out.extend(c_field_decl(field) for field in fields)
        out.append(f"}} {struct_name};")
        out.append("")
        out.append(
            f"int {prefix}_{msg['c_struct']}_encode(const {struct_name}* msg,"
        )
        out.append("                                   uint8_t* out, size_t out_capacity);")
        out.append(
            f"arc_result_t {prefix}_{msg['c_struct']}_decode(const uint8_t* in, size_t len,"
        )
        out.append(f"                                            {struct_name}* msg);")
        out.append("")

    out.append("#ifdef __cplusplus")
    out.append("}")
    out.append("#endif")
    out.append("")
    out.append(f"#endif  // {guard}")
    return "\n".join(out) + "\n"


def generate_c_source(family: dict) -> str:
    header = Path(family["c_target"]).name + ".h"
    prefix = family["c_type_prefix"]
    type_prefix = family["type_prefix"]
    out: list[str] = []
    out.append(generated_banner("//").rstrip())
    out.append("")
    out.append(f'#include "{header}"')
    out.append("")

    for msg in family["messages"]:
        fields = msg.get("payload", [])
        if not fields:
            continue
        struct_name = f"{prefix}_{msg['c_struct']}_t"
        size_name = f"{type_prefix}_{msg['name']}_PAYLOAD_SIZE"
        func = f"{prefix}_{msg['c_struct']}"
        out.append(f"int {func}_encode(const {struct_name}* msg,")
        out.append("                                   uint8_t* out, size_t out_capacity)")
        out.append("{")
        out.append("    if (msg == NULL || out == NULL) return ARC_ERR_BAD_ARG;")
        out.append(f"    if (out_capacity < {size_name}) return ARC_ERR_BUFFER;")
        offset = 0
        for field in fields:
            out.extend(c_encode_field(field, offset))
            offset += TYPE_INFO[field["type"]][1]
        out.append(f"    return {size_name};")
        out.append("}")
        out.append("")
        out.append(f"arc_result_t {func}_decode(const uint8_t* in, size_t len,")
        out.append(f"                                            {struct_name}* msg)")
        out.append("{")
        out.append("    if (in == NULL || msg == NULL) return ARC_ERR_BAD_ARG;")
        out.append(f"    if (len != {size_name}) return ARC_ERR_BAD_LENGTH;")
        offset = 0
        for field in fields:
            out.extend(c_decode_field(field, offset))
            offset += TYPE_INFO[field["type"]][1]
        out.append("    return ARC_OK;")
        out.append("}")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def py_class(message: dict) -> str:
    return message.get("class") or "".join(part.title() for part in message["name"].split("_"))


def py_encode_expr(field: dict) -> str:
    name = field["name"]
    typ = field["type"]
    helper = TYPE_INFO[typ][3]
    signed = ", signed=True" if TYPE_INFO[typ][2] else ""
    return f'{helper}(self.{name}, "{name}").to_bytes({TYPE_INFO[typ][1]}, "big"{signed})'


def py_decode_expr(field: dict, start: int) -> str:
    name = field["name"]
    typ = field["type"]
    end = start + TYPE_INFO[typ][1]
    signed = ", signed=True" if TYPE_INFO[typ][2] else ""
    if TYPE_INFO[typ][1] == 1 and typ == "u8":
        return f"{name}=payload[{start}]"
    return f'{name}=int.from_bytes(payload[{start}:{end}], "big"{signed})'


def generate_python(schema: dict) -> str:
    out: list[str] = []
    out.append(generated_banner("#").rstrip())
    out.append("")
    out.append("from __future__ import annotations")
    out.append("")
    out.append("from dataclasses import dataclass")
    out.append("from enum import IntEnum")
    out.append("")
    out.append("from . import protocol")
    out.append("")
    out.append("")
    out.append("class MessageError(ValueError):")
    out.append('    """Raised when a generated message payload is malformed."""')
    out.append("")

    for family in schema["families"]:
        out.append("")
        out.append(f"class {family['python_enum']}(IntEnum):")
        for msg in family["messages"]:
            if family["name"] == "NETMGMT":
                out.append(f"    {msg['name']} = protocol.NETMGMT_{msg['name']}")
            else:
                out.append(f"    {msg['name']} = {parse_int(msg['type']):#04x}")
        out.append("")

        for const in family.get("constants", []):
            out.append(f"{family['name']}_{const['name']} = {parse_int(const['value']):#04x}")
        if family.get("constants"):
            out.append("")

        for msg in family["messages"]:
            fields = msg.get("payload", [])
            if not fields:
                continue
            class_name = py_class(msg)
            size = payload_size(msg)
            out.append("")
            out.append("@dataclass(frozen=True)")
            out.append(f"class {class_name}:")
            for field in fields:
                out.append(f"    {field['name']}: int")
            out.append("")
            out.append("    def encode(self) -> bytes:")
            if len(fields) == 1:
                out.append(f"        return {py_encode_expr(fields[0])}")
            else:
                out.append("        return b\"\".join((")
                for field in fields:
                    out.append(f"            {py_encode_expr(field)},")
                out.append("        ))")
            out.append("")
            out.append("    @classmethod")
            out.append(f"    def decode(cls, payload: bytes) -> \"{class_name}\":")
            out.append(f'        _require_len(payload, {size}, "{family["name"]} {msg["name"]}")')
            if len(fields) == 1:
                out.append(f"        return cls({py_decode_expr(fields[0], 0)})")
            else:
                out.append("        return cls(")
                offset = 0
                for field in fields:
                    out.append(f"            {py_decode_expr(field, offset)},")
                    offset += TYPE_INFO[field["type"]][1]
                out.append("        )")
            out.append("")

    for family in schema["families"]:
        decode_name = f"decode_{family['name'].lower()}"
        enum_name = family["python_enum"]
        out.append("")
        out.append(f"def {decode_name}(type: int, payload: bytes) -> object | None:")
        out.append(f"    msg_type = {enum_name}(type)")
        for msg in family["messages"]:
            if msg.get("payload"):
                out.append(f"    if msg_type is {enum_name}.{msg['name']}:")
                out.append(f"        return {py_class(msg)}.decode(payload)")
        out.append("    _require_empty(payload, msg_type.name)")
        out.append("    return None")
        out.append("")
    out.append("")
    out.append("def _require_len(payload: bytes, expected: int, name: str) -> None:")
    out.append("    if len(payload) != expected:")
    out.append("        raise MessageError(f\"{name} payload must be {expected} bytes\")")
    out.append("")
    out.append("")
    out.append("def _require_empty(payload: bytes, name: str) -> None:")
    out.append("    if payload:")
    out.append("        raise MessageError(f\"{name} payload must be empty\")")
    out.append("")
    for helper, min_value, max_value, typename in (
        ("_u8", 0, 0xFF, "one byte"),
        ("_i8", -128, 127, "signed one byte"),
        ("_i16", -32768, 32767, "signed two bytes"),
        ("_u16", 0, 0xFFFF, "two bytes"),
        ("_i32", -2147483648, 2147483647, "signed four bytes"),
        ("_u32", 0, 0xFFFFFFFF, "four bytes"),
    ):
        out.append("")
        out.append(f"def {helper}(value: int, name: str) -> int:")
        out.append(f"    if not {min_value} <= value <= {max_value}:")
        out.append(f"        raise MessageError(f\"{{name}} must fit in {typename}\")")
        out.append("    return value")
    out.append("")
    return "\n".join(out)


def generated_files(schema: dict) -> dict[Path, str]:
    files: dict[Path, str] = {}
    for family in schema["families"]:
        target = ROOT / family["c_target"]
        files[target.with_suffix(".h")] = generate_c_header(family)
        files[target.with_suffix(".c")] = generate_c_source(family)
    files[PY_TARGET] = generate_python(schema)
    return files


def load_schema() -> dict:
    with SCHEMA_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    stale: list[Path] = []
    for path, content in generated_files(load_schema()).items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    if stale:
        print("Generated files are stale:")
        for path in stale:
            print(f"  {path.relative_to(ROOT)}")
        print("Run: python tools/generate_messages.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
