// AUTO-GENERATED by tools/generate_messages.py.
// Source schema: schema/messages.json
// Edit the schema and regenerate; do not hand-edit this file.

#ifndef ARC_MESSAGES_FC_COORD_H
#define ARC_MESSAGES_FC_COORD_H

#include "arc_protocol.h"

#ifdef __cplusplus
extern "C" {
#endif

// Message types.
#define ARC_FC_COORD_FLIGHT_TELEMETRY    0x10
#define ARC_FC_COORD_AIRBRAKE_TELEMETRY  0x11
#define ARC_FC_COORD_PAYLOAD_TELEMETRY   0x12

#define ARC_FC_COORD_STAGE_UNKNOWN       0x00
#define ARC_FC_COORD_STAGE_PAD           0x01
#define ARC_FC_COORD_STAGE_BOOST         0x02
#define ARC_FC_COORD_STAGE_COAST         0x03
#define ARC_FC_COORD_STAGE_DROGUE        0x04
#define ARC_FC_COORD_STAGE_MAIN          0x05
#define ARC_FC_COORD_STAGE_LANDED        0x06
#define ARC_FC_COORD_GPS_FIX_NONE        0x00
#define ARC_FC_COORD_GPS_FIX_2D          0x01
#define ARC_FC_COORD_GPS_FIX_3D          0x02
#define ARC_FC_COORD_GPS_FIX_DGPS        0x03
#define ARC_FC_COORD_GPS_FIX_RTK_FLOAT   0x04
#define ARC_FC_COORD_GPS_FIX_RTK_FIXED   0x05

#define ARC_FC_COORD_FLIGHT_TELEMETRY_PAYLOAD_SIZE 0x28

typedef struct {
    uint32_t time_ms;
    uint8_t stage;
    int16_t accel_x_mg;
    int16_t accel_y_mg;
    int16_t accel_z_mg;
    int16_t vel_x_cms;
    int16_t vel_y_cms;
    int16_t vel_z_cms;
    int32_t lat_e7;
    int32_t lon_e7;
    int32_t alt_cm;
    int16_t temp_cdeg;
    uint16_t voltage_mv;
    uint8_t gps_fix_quality;
    int16_t roll_cdeg;
    int16_t pitch_cdeg;
    int16_t yaw_cdeg;
} arc_fc_coord_flight_telemetry_t;

int arc_fc_coord_flight_telemetry_encode(const arc_fc_coord_flight_telemetry_t* msg,
                                   uint8_t* out, size_t out_capacity);
arc_result_t arc_fc_coord_flight_telemetry_decode(const uint8_t* in, size_t len,
                                            arc_fc_coord_flight_telemetry_t* msg);

#define ARC_FC_COORD_AIRBRAKE_TELEMETRY_PAYLOAD_SIZE 0x29

typedef struct {
    uint32_t time_ms;
    uint8_t stage;
    int16_t accel_x_mg;
    int16_t accel_y_mg;
    int16_t accel_z_mg;
    int16_t vel_x_cms;
    int16_t vel_y_cms;
    int16_t vel_z_cms;
    int16_t temp_cdeg;
    uint16_t voltage_mv;
    int16_t roll_cdeg;
    int16_t pitch_cdeg;
    int16_t yaw_cdeg;
    int16_t airbrake_angle_cdeg;
    int32_t predicted_apogee_cm;
    int32_t original_apogee_estimate_cm;
    int32_t blueraven_alt_cm;
} arc_fc_coord_airbrake_telemetry_t;

int arc_fc_coord_airbrake_telemetry_encode(const arc_fc_coord_airbrake_telemetry_t* msg,
                                   uint8_t* out, size_t out_capacity);
arc_result_t arc_fc_coord_airbrake_telemetry_decode(const uint8_t* in, size_t len,
                                            arc_fc_coord_airbrake_telemetry_t* msg);

#define ARC_FC_COORD_PAYLOAD_TELEMETRY_PAYLOAD_SIZE 0x24

typedef struct {
    uint32_t time_ms;
    uint8_t stage;
    int16_t accel_x_mg;
    int16_t accel_y_mg;
    int16_t accel_z_mg;
    int16_t vel_x_cms;
    int16_t vel_y_cms;
    int16_t vel_z_cms;
    int16_t temp_cdeg;
    uint16_t voltage_mv;
    int16_t roll_cdeg;
    int16_t pitch_cdeg;
    int16_t yaw_cdeg;
    int32_t motor_x_um;
    int32_t motor_y_um;
    uint8_t percent_complete;
} arc_fc_coord_payload_telemetry_t;

int arc_fc_coord_payload_telemetry_encode(const arc_fc_coord_payload_telemetry_t* msg,
                                   uint8_t* out, size_t out_capacity);
arc_result_t arc_fc_coord_payload_telemetry_decode(const uint8_t* in, size_t len,
                                            arc_fc_coord_payload_telemetry_t* msg);

#ifdef __cplusplus
}
#endif

#endif  // ARC_MESSAGES_FC_COORD_H
