// AUTO-GENERATED by tools/generate_messages.py.
// Source schema: schema/messages.json
// Edit the schema and regenerate; do not hand-edit this file.

#include "arc_messages_fc_coord.h"

int arc_fc_coord_flight_telemetry_encode(const arc_fc_coord_flight_telemetry_t* msg,
                                   uint8_t* out, size_t out_capacity)
{
    if (msg == NULL || out == NULL) return ARC_ERR_BAD_ARG;
    if (out_capacity < ARC_FC_COORD_FLIGHT_TELEMETRY_PAYLOAD_SIZE) return ARC_ERR_BUFFER;
    out[0] = (uint8_t)((msg->time_ms >> 24) & 0xFF);
    out[1] = (uint8_t)((msg->time_ms >> 16) & 0xFF);
    out[2] = (uint8_t)((msg->time_ms >> 8) & 0xFF);
    out[3] = (uint8_t)(msg->time_ms & 0xFF);
    out[4] = msg->stage;
    uint16_t accel_x_mg_wire = (uint16_t)msg->accel_x_mg;
    out[5] = (uint8_t)((accel_x_mg_wire >> 8) & 0xFF);
    out[6] = (uint8_t)(accel_x_mg_wire & 0xFF);
    uint16_t accel_y_mg_wire = (uint16_t)msg->accel_y_mg;
    out[7] = (uint8_t)((accel_y_mg_wire >> 8) & 0xFF);
    out[8] = (uint8_t)(accel_y_mg_wire & 0xFF);
    uint16_t accel_z_mg_wire = (uint16_t)msg->accel_z_mg;
    out[9] = (uint8_t)((accel_z_mg_wire >> 8) & 0xFF);
    out[10] = (uint8_t)(accel_z_mg_wire & 0xFF);
    uint16_t vel_x_cms_wire = (uint16_t)msg->vel_x_cms;
    out[11] = (uint8_t)((vel_x_cms_wire >> 8) & 0xFF);
    out[12] = (uint8_t)(vel_x_cms_wire & 0xFF);
    uint16_t vel_y_cms_wire = (uint16_t)msg->vel_y_cms;
    out[13] = (uint8_t)((vel_y_cms_wire >> 8) & 0xFF);
    out[14] = (uint8_t)(vel_y_cms_wire & 0xFF);
    uint16_t vel_z_cms_wire = (uint16_t)msg->vel_z_cms;
    out[15] = (uint8_t)((vel_z_cms_wire >> 8) & 0xFF);
    out[16] = (uint8_t)(vel_z_cms_wire & 0xFF);
    uint32_t lat_e7_wire = (uint32_t)msg->lat_e7;
    out[17] = (uint8_t)((lat_e7_wire >> 24) & 0xFF);
    out[18] = (uint8_t)((lat_e7_wire >> 16) & 0xFF);
    out[19] = (uint8_t)((lat_e7_wire >> 8) & 0xFF);
    out[20] = (uint8_t)(lat_e7_wire & 0xFF);
    uint32_t lon_e7_wire = (uint32_t)msg->lon_e7;
    out[21] = (uint8_t)((lon_e7_wire >> 24) & 0xFF);
    out[22] = (uint8_t)((lon_e7_wire >> 16) & 0xFF);
    out[23] = (uint8_t)((lon_e7_wire >> 8) & 0xFF);
    out[24] = (uint8_t)(lon_e7_wire & 0xFF);
    uint32_t alt_cm_wire = (uint32_t)msg->alt_cm;
    out[25] = (uint8_t)((alt_cm_wire >> 24) & 0xFF);
    out[26] = (uint8_t)((alt_cm_wire >> 16) & 0xFF);
    out[27] = (uint8_t)((alt_cm_wire >> 8) & 0xFF);
    out[28] = (uint8_t)(alt_cm_wire & 0xFF);
    uint16_t temp_cdeg_wire = (uint16_t)msg->temp_cdeg;
    out[29] = (uint8_t)((temp_cdeg_wire >> 8) & 0xFF);
    out[30] = (uint8_t)(temp_cdeg_wire & 0xFF);
    out[31] = (uint8_t)((msg->voltage_mv >> 8) & 0xFF);
    out[32] = (uint8_t)(msg->voltage_mv & 0xFF);
    out[33] = msg->gps_fix_quality;
    uint16_t roll_cdeg_wire = (uint16_t)msg->roll_cdeg;
    out[34] = (uint8_t)((roll_cdeg_wire >> 8) & 0xFF);
    out[35] = (uint8_t)(roll_cdeg_wire & 0xFF);
    uint16_t pitch_cdeg_wire = (uint16_t)msg->pitch_cdeg;
    out[36] = (uint8_t)((pitch_cdeg_wire >> 8) & 0xFF);
    out[37] = (uint8_t)(pitch_cdeg_wire & 0xFF);
    uint16_t yaw_cdeg_wire = (uint16_t)msg->yaw_cdeg;
    out[38] = (uint8_t)((yaw_cdeg_wire >> 8) & 0xFF);
    out[39] = (uint8_t)(yaw_cdeg_wire & 0xFF);
    return ARC_FC_COORD_FLIGHT_TELEMETRY_PAYLOAD_SIZE;
}

arc_result_t arc_fc_coord_flight_telemetry_decode(const uint8_t* in, size_t len,
                                            arc_fc_coord_flight_telemetry_t* msg)
{
    if (in == NULL || msg == NULL) return ARC_ERR_BAD_ARG;
    if (len != ARC_FC_COORD_FLIGHT_TELEMETRY_PAYLOAD_SIZE) return ARC_ERR_BAD_LENGTH;
    msg->time_ms =
        ((uint32_t)in[0] << 24) |
        ((uint32_t)in[1] << 16) |
        ((uint32_t)in[2] << 8)  |
        ((uint32_t)in[3]);
    msg->stage = in[4];
    msg->accel_x_mg = (int16_t)(((uint16_t)in[5] << 8) | (uint16_t)in[6]);
    msg->accel_y_mg = (int16_t)(((uint16_t)in[7] << 8) | (uint16_t)in[8]);
    msg->accel_z_mg = (int16_t)(((uint16_t)in[9] << 8) | (uint16_t)in[10]);
    msg->vel_x_cms = (int16_t)(((uint16_t)in[11] << 8) | (uint16_t)in[12]);
    msg->vel_y_cms = (int16_t)(((uint16_t)in[13] << 8) | (uint16_t)in[14]);
    msg->vel_z_cms = (int16_t)(((uint16_t)in[15] << 8) | (uint16_t)in[16]);
    msg->lat_e7 = (int32_t)(
        ((uint32_t)in[17] << 24) |
        ((uint32_t)in[18] << 16) |
        ((uint32_t)in[19] << 8)  |
        ((uint32_t)in[20]));
    msg->lon_e7 = (int32_t)(
        ((uint32_t)in[21] << 24) |
        ((uint32_t)in[22] << 16) |
        ((uint32_t)in[23] << 8)  |
        ((uint32_t)in[24]));
    msg->alt_cm = (int32_t)(
        ((uint32_t)in[25] << 24) |
        ((uint32_t)in[26] << 16) |
        ((uint32_t)in[27] << 8)  |
        ((uint32_t)in[28]));
    msg->temp_cdeg = (int16_t)(((uint16_t)in[29] << 8) | (uint16_t)in[30]);
    msg->voltage_mv = ((uint16_t)in[31] << 8) | (uint16_t)in[32];
    msg->gps_fix_quality = in[33];
    msg->roll_cdeg = (int16_t)(((uint16_t)in[34] << 8) | (uint16_t)in[35]);
    msg->pitch_cdeg = (int16_t)(((uint16_t)in[36] << 8) | (uint16_t)in[37]);
    msg->yaw_cdeg = (int16_t)(((uint16_t)in[38] << 8) | (uint16_t)in[39]);
    return ARC_OK;
}

int arc_fc_coord_airbrake_telemetry_encode(const arc_fc_coord_airbrake_telemetry_t* msg,
                                   uint8_t* out, size_t out_capacity)
{
    if (msg == NULL || out == NULL) return ARC_ERR_BAD_ARG;
    if (out_capacity < ARC_FC_COORD_AIRBRAKE_TELEMETRY_PAYLOAD_SIZE) return ARC_ERR_BUFFER;
    out[0] = (uint8_t)((msg->time_ms >> 24) & 0xFF);
    out[1] = (uint8_t)((msg->time_ms >> 16) & 0xFF);
    out[2] = (uint8_t)((msg->time_ms >> 8) & 0xFF);
    out[3] = (uint8_t)(msg->time_ms & 0xFF);
    out[4] = msg->stage;
    uint16_t accel_x_mg_wire = (uint16_t)msg->accel_x_mg;
    out[5] = (uint8_t)((accel_x_mg_wire >> 8) & 0xFF);
    out[6] = (uint8_t)(accel_x_mg_wire & 0xFF);
    uint16_t accel_y_mg_wire = (uint16_t)msg->accel_y_mg;
    out[7] = (uint8_t)((accel_y_mg_wire >> 8) & 0xFF);
    out[8] = (uint8_t)(accel_y_mg_wire & 0xFF);
    uint16_t accel_z_mg_wire = (uint16_t)msg->accel_z_mg;
    out[9] = (uint8_t)((accel_z_mg_wire >> 8) & 0xFF);
    out[10] = (uint8_t)(accel_z_mg_wire & 0xFF);
    uint16_t vel_x_cms_wire = (uint16_t)msg->vel_x_cms;
    out[11] = (uint8_t)((vel_x_cms_wire >> 8) & 0xFF);
    out[12] = (uint8_t)(vel_x_cms_wire & 0xFF);
    uint16_t vel_y_cms_wire = (uint16_t)msg->vel_y_cms;
    out[13] = (uint8_t)((vel_y_cms_wire >> 8) & 0xFF);
    out[14] = (uint8_t)(vel_y_cms_wire & 0xFF);
    uint16_t vel_z_cms_wire = (uint16_t)msg->vel_z_cms;
    out[15] = (uint8_t)((vel_z_cms_wire >> 8) & 0xFF);
    out[16] = (uint8_t)(vel_z_cms_wire & 0xFF);
    uint16_t temp_cdeg_wire = (uint16_t)msg->temp_cdeg;
    out[17] = (uint8_t)((temp_cdeg_wire >> 8) & 0xFF);
    out[18] = (uint8_t)(temp_cdeg_wire & 0xFF);
    out[19] = (uint8_t)((msg->voltage_mv >> 8) & 0xFF);
    out[20] = (uint8_t)(msg->voltage_mv & 0xFF);
    uint16_t roll_cdeg_wire = (uint16_t)msg->roll_cdeg;
    out[21] = (uint8_t)((roll_cdeg_wire >> 8) & 0xFF);
    out[22] = (uint8_t)(roll_cdeg_wire & 0xFF);
    uint16_t pitch_cdeg_wire = (uint16_t)msg->pitch_cdeg;
    out[23] = (uint8_t)((pitch_cdeg_wire >> 8) & 0xFF);
    out[24] = (uint8_t)(pitch_cdeg_wire & 0xFF);
    uint16_t yaw_cdeg_wire = (uint16_t)msg->yaw_cdeg;
    out[25] = (uint8_t)((yaw_cdeg_wire >> 8) & 0xFF);
    out[26] = (uint8_t)(yaw_cdeg_wire & 0xFF);
    uint16_t airbrake_angle_cdeg_wire = (uint16_t)msg->airbrake_angle_cdeg;
    out[27] = (uint8_t)((airbrake_angle_cdeg_wire >> 8) & 0xFF);
    out[28] = (uint8_t)(airbrake_angle_cdeg_wire & 0xFF);
    uint32_t predicted_apogee_cm_wire = (uint32_t)msg->predicted_apogee_cm;
    out[29] = (uint8_t)((predicted_apogee_cm_wire >> 24) & 0xFF);
    out[30] = (uint8_t)((predicted_apogee_cm_wire >> 16) & 0xFF);
    out[31] = (uint8_t)((predicted_apogee_cm_wire >> 8) & 0xFF);
    out[32] = (uint8_t)(predicted_apogee_cm_wire & 0xFF);
    uint32_t original_apogee_estimate_cm_wire = (uint32_t)msg->original_apogee_estimate_cm;
    out[33] = (uint8_t)((original_apogee_estimate_cm_wire >> 24) & 0xFF);
    out[34] = (uint8_t)((original_apogee_estimate_cm_wire >> 16) & 0xFF);
    out[35] = (uint8_t)((original_apogee_estimate_cm_wire >> 8) & 0xFF);
    out[36] = (uint8_t)(original_apogee_estimate_cm_wire & 0xFF);
    uint32_t blueraven_alt_cm_wire = (uint32_t)msg->blueraven_alt_cm;
    out[37] = (uint8_t)((blueraven_alt_cm_wire >> 24) & 0xFF);
    out[38] = (uint8_t)((blueraven_alt_cm_wire >> 16) & 0xFF);
    out[39] = (uint8_t)((blueraven_alt_cm_wire >> 8) & 0xFF);
    out[40] = (uint8_t)(blueraven_alt_cm_wire & 0xFF);
    return ARC_FC_COORD_AIRBRAKE_TELEMETRY_PAYLOAD_SIZE;
}

arc_result_t arc_fc_coord_airbrake_telemetry_decode(const uint8_t* in, size_t len,
                                            arc_fc_coord_airbrake_telemetry_t* msg)
{
    if (in == NULL || msg == NULL) return ARC_ERR_BAD_ARG;
    if (len != ARC_FC_COORD_AIRBRAKE_TELEMETRY_PAYLOAD_SIZE) return ARC_ERR_BAD_LENGTH;
    msg->time_ms =
        ((uint32_t)in[0] << 24) |
        ((uint32_t)in[1] << 16) |
        ((uint32_t)in[2] << 8)  |
        ((uint32_t)in[3]);
    msg->stage = in[4];
    msg->accel_x_mg = (int16_t)(((uint16_t)in[5] << 8) | (uint16_t)in[6]);
    msg->accel_y_mg = (int16_t)(((uint16_t)in[7] << 8) | (uint16_t)in[8]);
    msg->accel_z_mg = (int16_t)(((uint16_t)in[9] << 8) | (uint16_t)in[10]);
    msg->vel_x_cms = (int16_t)(((uint16_t)in[11] << 8) | (uint16_t)in[12]);
    msg->vel_y_cms = (int16_t)(((uint16_t)in[13] << 8) | (uint16_t)in[14]);
    msg->vel_z_cms = (int16_t)(((uint16_t)in[15] << 8) | (uint16_t)in[16]);
    msg->temp_cdeg = (int16_t)(((uint16_t)in[17] << 8) | (uint16_t)in[18]);
    msg->voltage_mv = ((uint16_t)in[19] << 8) | (uint16_t)in[20];
    msg->roll_cdeg = (int16_t)(((uint16_t)in[21] << 8) | (uint16_t)in[22]);
    msg->pitch_cdeg = (int16_t)(((uint16_t)in[23] << 8) | (uint16_t)in[24]);
    msg->yaw_cdeg = (int16_t)(((uint16_t)in[25] << 8) | (uint16_t)in[26]);
    msg->airbrake_angle_cdeg = (int16_t)(((uint16_t)in[27] << 8) | (uint16_t)in[28]);
    msg->predicted_apogee_cm = (int32_t)(
        ((uint32_t)in[29] << 24) |
        ((uint32_t)in[30] << 16) |
        ((uint32_t)in[31] << 8)  |
        ((uint32_t)in[32]));
    msg->original_apogee_estimate_cm = (int32_t)(
        ((uint32_t)in[33] << 24) |
        ((uint32_t)in[34] << 16) |
        ((uint32_t)in[35] << 8)  |
        ((uint32_t)in[36]));
    msg->blueraven_alt_cm = (int32_t)(
        ((uint32_t)in[37] << 24) |
        ((uint32_t)in[38] << 16) |
        ((uint32_t)in[39] << 8)  |
        ((uint32_t)in[40]));
    return ARC_OK;
}

int arc_fc_coord_payload_telemetry_encode(const arc_fc_coord_payload_telemetry_t* msg,
                                   uint8_t* out, size_t out_capacity)
{
    if (msg == NULL || out == NULL) return ARC_ERR_BAD_ARG;
    if (out_capacity < ARC_FC_COORD_PAYLOAD_TELEMETRY_PAYLOAD_SIZE) return ARC_ERR_BUFFER;
    out[0] = (uint8_t)((msg->time_ms >> 24) & 0xFF);
    out[1] = (uint8_t)((msg->time_ms >> 16) & 0xFF);
    out[2] = (uint8_t)((msg->time_ms >> 8) & 0xFF);
    out[3] = (uint8_t)(msg->time_ms & 0xFF);
    out[4] = msg->stage;
    uint16_t accel_x_mg_wire = (uint16_t)msg->accel_x_mg;
    out[5] = (uint8_t)((accel_x_mg_wire >> 8) & 0xFF);
    out[6] = (uint8_t)(accel_x_mg_wire & 0xFF);
    uint16_t accel_y_mg_wire = (uint16_t)msg->accel_y_mg;
    out[7] = (uint8_t)((accel_y_mg_wire >> 8) & 0xFF);
    out[8] = (uint8_t)(accel_y_mg_wire & 0xFF);
    uint16_t accel_z_mg_wire = (uint16_t)msg->accel_z_mg;
    out[9] = (uint8_t)((accel_z_mg_wire >> 8) & 0xFF);
    out[10] = (uint8_t)(accel_z_mg_wire & 0xFF);
    uint16_t vel_x_cms_wire = (uint16_t)msg->vel_x_cms;
    out[11] = (uint8_t)((vel_x_cms_wire >> 8) & 0xFF);
    out[12] = (uint8_t)(vel_x_cms_wire & 0xFF);
    uint16_t vel_y_cms_wire = (uint16_t)msg->vel_y_cms;
    out[13] = (uint8_t)((vel_y_cms_wire >> 8) & 0xFF);
    out[14] = (uint8_t)(vel_y_cms_wire & 0xFF);
    uint16_t vel_z_cms_wire = (uint16_t)msg->vel_z_cms;
    out[15] = (uint8_t)((vel_z_cms_wire >> 8) & 0xFF);
    out[16] = (uint8_t)(vel_z_cms_wire & 0xFF);
    uint16_t temp_cdeg_wire = (uint16_t)msg->temp_cdeg;
    out[17] = (uint8_t)((temp_cdeg_wire >> 8) & 0xFF);
    out[18] = (uint8_t)(temp_cdeg_wire & 0xFF);
    out[19] = (uint8_t)((msg->voltage_mv >> 8) & 0xFF);
    out[20] = (uint8_t)(msg->voltage_mv & 0xFF);
    uint16_t roll_cdeg_wire = (uint16_t)msg->roll_cdeg;
    out[21] = (uint8_t)((roll_cdeg_wire >> 8) & 0xFF);
    out[22] = (uint8_t)(roll_cdeg_wire & 0xFF);
    uint16_t pitch_cdeg_wire = (uint16_t)msg->pitch_cdeg;
    out[23] = (uint8_t)((pitch_cdeg_wire >> 8) & 0xFF);
    out[24] = (uint8_t)(pitch_cdeg_wire & 0xFF);
    uint16_t yaw_cdeg_wire = (uint16_t)msg->yaw_cdeg;
    out[25] = (uint8_t)((yaw_cdeg_wire >> 8) & 0xFF);
    out[26] = (uint8_t)(yaw_cdeg_wire & 0xFF);
    uint32_t motor_x_um_wire = (uint32_t)msg->motor_x_um;
    out[27] = (uint8_t)((motor_x_um_wire >> 24) & 0xFF);
    out[28] = (uint8_t)((motor_x_um_wire >> 16) & 0xFF);
    out[29] = (uint8_t)((motor_x_um_wire >> 8) & 0xFF);
    out[30] = (uint8_t)(motor_x_um_wire & 0xFF);
    uint32_t motor_y_um_wire = (uint32_t)msg->motor_y_um;
    out[31] = (uint8_t)((motor_y_um_wire >> 24) & 0xFF);
    out[32] = (uint8_t)((motor_y_um_wire >> 16) & 0xFF);
    out[33] = (uint8_t)((motor_y_um_wire >> 8) & 0xFF);
    out[34] = (uint8_t)(motor_y_um_wire & 0xFF);
    out[35] = msg->percent_complete;
    return ARC_FC_COORD_PAYLOAD_TELEMETRY_PAYLOAD_SIZE;
}

arc_result_t arc_fc_coord_payload_telemetry_decode(const uint8_t* in, size_t len,
                                            arc_fc_coord_payload_telemetry_t* msg)
{
    if (in == NULL || msg == NULL) return ARC_ERR_BAD_ARG;
    if (len != ARC_FC_COORD_PAYLOAD_TELEMETRY_PAYLOAD_SIZE) return ARC_ERR_BAD_LENGTH;
    msg->time_ms =
        ((uint32_t)in[0] << 24) |
        ((uint32_t)in[1] << 16) |
        ((uint32_t)in[2] << 8)  |
        ((uint32_t)in[3]);
    msg->stage = in[4];
    msg->accel_x_mg = (int16_t)(((uint16_t)in[5] << 8) | (uint16_t)in[6]);
    msg->accel_y_mg = (int16_t)(((uint16_t)in[7] << 8) | (uint16_t)in[8]);
    msg->accel_z_mg = (int16_t)(((uint16_t)in[9] << 8) | (uint16_t)in[10]);
    msg->vel_x_cms = (int16_t)(((uint16_t)in[11] << 8) | (uint16_t)in[12]);
    msg->vel_y_cms = (int16_t)(((uint16_t)in[13] << 8) | (uint16_t)in[14]);
    msg->vel_z_cms = (int16_t)(((uint16_t)in[15] << 8) | (uint16_t)in[16]);
    msg->temp_cdeg = (int16_t)(((uint16_t)in[17] << 8) | (uint16_t)in[18]);
    msg->voltage_mv = ((uint16_t)in[19] << 8) | (uint16_t)in[20];
    msg->roll_cdeg = (int16_t)(((uint16_t)in[21] << 8) | (uint16_t)in[22]);
    msg->pitch_cdeg = (int16_t)(((uint16_t)in[23] << 8) | (uint16_t)in[24]);
    msg->yaw_cdeg = (int16_t)(((uint16_t)in[25] << 8) | (uint16_t)in[26]);
    msg->motor_x_um = (int32_t)(
        ((uint32_t)in[27] << 24) |
        ((uint32_t)in[28] << 16) |
        ((uint32_t)in[29] << 8)  |
        ((uint32_t)in[30]));
    msg->motor_y_um = (int32_t)(
        ((uint32_t)in[31] << 24) |
        ((uint32_t)in[32] << 16) |
        ((uint32_t)in[33] << 8)  |
        ((uint32_t)in[34]));
    msg->percent_complete = in[35];
    return ARC_OK;
}

int arc_fc_coord_set_airbrake_angle_encode(const arc_fc_coord_set_airbrake_angle_t* msg,
                                   uint8_t* out, size_t out_capacity)
{
    if (msg == NULL || out == NULL) return ARC_ERR_BAD_ARG;
    if (out_capacity < ARC_FC_COORD_SET_AIRBRAKE_ANGLE_PAYLOAD_SIZE) return ARC_ERR_BUFFER;
    uint16_t angle_cdeg_wire = (uint16_t)msg->angle_cdeg;
    out[0] = (uint8_t)((angle_cdeg_wire >> 8) & 0xFF);
    out[1] = (uint8_t)(angle_cdeg_wire & 0xFF);
    return ARC_FC_COORD_SET_AIRBRAKE_ANGLE_PAYLOAD_SIZE;
}

arc_result_t arc_fc_coord_set_airbrake_angle_decode(const uint8_t* in, size_t len,
                                            arc_fc_coord_set_airbrake_angle_t* msg)
{
    if (in == NULL || msg == NULL) return ARC_ERR_BAD_ARG;
    if (len != ARC_FC_COORD_SET_AIRBRAKE_ANGLE_PAYLOAD_SIZE) return ARC_ERR_BAD_LENGTH;
    msg->angle_cdeg = (int16_t)(((uint16_t)in[0] << 8) | (uint16_t)in[1]);
    return ARC_OK;
}
