// AUTO-GENERATED by tools/generate_messages.py.
// Source schema: schema/messages.json
// Edit the schema and regenerate; do not hand-edit this file.

#ifndef ARC_MESSAGES_RADIO_H
#define ARC_MESSAGES_RADIO_H

#include "arc_protocol.h"

#ifdef __cplusplus
extern "C" {
#endif

// Message types.
#define ARC_RADIO_SET_FREQUENCY          0x01
#define ARC_RADIO_SET_TX_POWER           0x02
#define ARC_RADIO_GET_STATUS             0x03
#define ARC_RADIO_SET_PHY_PROFILE        0x04
#define ARC_RADIO_START_HOPPING          0x05
#define ARC_RADIO_DATA_DOWNLINK          0x06
#define ARC_RADIO_STATUS_REPORT          0x10

#define ARC_RADIO_ERR_TX_BUSY            0x01
#define ARC_RADIO_ERR_PLL_UNLOCK         0x02
#define ARC_RADIO_ERR_OVERTEMP           0x04
#define ARC_RADIO_ERR_RX_OVERRUN         0x08
#define ARC_RADIO_PHY_PROFILE_SAFE_BW125 0x00
#define ARC_RADIO_PHY_PROFILE_FAST_BW500 0x01

#define ARC_RADIO_SET_FREQUENCY_PAYLOAD_SIZE 0x04

typedef struct {
    uint32_t frequency_hz;
} arc_radio_set_frequency_t;

int arc_radio_set_frequency_encode(const arc_radio_set_frequency_t* msg,
                                   uint8_t* out, size_t out_capacity);
arc_result_t arc_radio_set_frequency_decode(const uint8_t* in, size_t len,
                                            arc_radio_set_frequency_t* msg);

#define ARC_RADIO_SET_TX_POWER_PAYLOAD_SIZE 0x01

typedef struct {
    int8_t tx_power_dbm;
} arc_radio_set_tx_power_t;

int arc_radio_set_tx_power_encode(const arc_radio_set_tx_power_t* msg,
                                   uint8_t* out, size_t out_capacity);
arc_result_t arc_radio_set_tx_power_decode(const uint8_t* in, size_t len,
                                            arc_radio_set_tx_power_t* msg);

#define ARC_RADIO_SET_PHY_PROFILE_PAYLOAD_SIZE 0x01

typedef struct {
    uint8_t profile_id;
} arc_radio_set_phy_profile_t;

int arc_radio_set_phy_profile_encode(const arc_radio_set_phy_profile_t* msg,
                                   uint8_t* out, size_t out_capacity);
arc_result_t arc_radio_set_phy_profile_decode(const uint8_t* in, size_t len,
                                            arc_radio_set_phy_profile_t* msg);

#define ARC_RADIO_STATUS_REPORT_PAYLOAD_SIZE 0x0C

typedef struct {
    uint32_t frequency_hz;
    int8_t tx_power_dbm;
    int8_t rssi_dbm;
    int8_t snr_db;
    uint8_t error_flags;
    uint16_t packets_rx;
    uint16_t packets_tx;
} arc_radio_status_report_t;

int arc_radio_status_report_encode(const arc_radio_status_report_t* msg,
                                   uint8_t* out, size_t out_capacity);
arc_result_t arc_radio_status_report_decode(const uint8_t* in, size_t len,
                                            arc_radio_status_report_t* msg);

#ifdef __cplusplus
}
#endif

#endif  // ARC_MESSAGES_RADIO_H
