// AUTO-GENERATED by tools/generate_messages.py.
// Source schema: schema/messages.json
// Edit the schema and regenerate; do not hand-edit this file.

#ifndef ARC_MESSAGES_NETMGMT_H
#define ARC_MESSAGES_NETMGMT_H

#include "arc_protocol.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ARC_NETMGMT_ACK_PAYLOAD_SIZE     0x02

typedef struct {
    uint16_t seq;
} arc_netmgmt_ack_t;

int arc_netmgmt_ack_encode(const arc_netmgmt_ack_t* msg,
                                   uint8_t* out, size_t out_capacity);
arc_result_t arc_netmgmt_ack_decode(const uint8_t* in, size_t len,
                                            arc_netmgmt_ack_t* msg);

#ifdef __cplusplus
}
#endif

#endif  // ARC_MESSAGES_NETMGMT_H
