"""ARC protocol primitives (Python implementation).

Byte-compatible with the C library at the repository root. This package is
the *shared source of truth* for the ARC wire format: framing, COBS, CRC,
the static router, the reliable transport state machine, and the per-family
message catalogs.

Both languages are validated against the same canonical vectors in
``vectors/test_vectors.txt`` (generated by the C ``gen_vectors`` tool), so
the two implementations cannot drift without a test failing.

Application code (Controllers, Senders, ground tools) should depend on this
package rather than reimplementing the wire format.
"""
