# AUTO-GENERATED by tools/generate_messages.py.
# Source schema: schema/messages.json
# Edit the schema and regenerate; do not hand-edit this file.

from __future__ import annotations

from dataclasses import dataclass
from enum import IntEnum

from . import protocol


class MessageError(ValueError):
    """Raised when a generated message payload is malformed."""


class NetMgmtType(IntEnum):
    HEARTBEAT = protocol.NETMGMT_HEARTBEAT
    ACK = protocol.NETMGMT_ACK
    SESSION_RESET = protocol.NETMGMT_SESSION_RESET


@dataclass(frozen=True)
class Ack:
    seq: int

    def encode(self) -> bytes:
        return _u16(self.seq, "seq").to_bytes(2, "big")

    @classmethod
    def decode(cls, payload: bytes) -> "Ack":
        _require_len(payload, 2, "NETMGMT ACK")
        return cls(seq=int.from_bytes(payload[0:2], "big"))


class FcCoordType(IntEnum):
    FLIGHT_TELEMETRY = 0x10
    AIRBRAKE_TELEMETRY = 0x11
    PAYLOAD_TELEMETRY = 0x12

FC_COORD_STAGE_UNKNOWN = 0x00
FC_COORD_STAGE_PAD = 0x01
FC_COORD_STAGE_BOOST = 0x02
FC_COORD_STAGE_COAST = 0x03
FC_COORD_STAGE_DROGUE = 0x04
FC_COORD_STAGE_MAIN = 0x05
FC_COORD_STAGE_LANDED = 0x06
FC_COORD_GPS_FIX_NONE = 0x00
FC_COORD_GPS_FIX_2D = 0x01
FC_COORD_GPS_FIX_3D = 0x02
FC_COORD_GPS_FIX_DGPS = 0x03
FC_COORD_GPS_FIX_RTK_FLOAT = 0x04
FC_COORD_GPS_FIX_RTK_FIXED = 0x05


@dataclass(frozen=True)
class FlightTelemetry:
    time_ms: int
    stage: int
    accel_x_mg: int
    accel_y_mg: int
    accel_z_mg: int
    vel_x_cms: int
    vel_y_cms: int
    vel_z_cms: int
    lat_e7: int
    lon_e7: int
    alt_cm: int
    temp_cdeg: int
    voltage_mv: int
    gps_fix_quality: int
    roll_cdeg: int
    pitch_cdeg: int
    yaw_cdeg: int

    def encode(self) -> bytes:
        return b"".join((
            _u32(self.time_ms, "time_ms").to_bytes(4, "big"),
            _u8(self.stage, "stage").to_bytes(1, "big"),
            _i16(self.accel_x_mg, "accel_x_mg").to_bytes(2, "big", signed=True),
            _i16(self.accel_y_mg, "accel_y_mg").to_bytes(2, "big", signed=True),
            _i16(self.accel_z_mg, "accel_z_mg").to_bytes(2, "big", signed=True),
            _i16(self.vel_x_cms, "vel_x_cms").to_bytes(2, "big", signed=True),
            _i16(self.vel_y_cms, "vel_y_cms").to_bytes(2, "big", signed=True),
            _i16(self.vel_z_cms, "vel_z_cms").to_bytes(2, "big", signed=True),
            _i32(self.lat_e7, "lat_e7").to_bytes(4, "big", signed=True),
            _i32(self.lon_e7, "lon_e7").to_bytes(4, "big", signed=True),
            _i32(self.alt_cm, "alt_cm").to_bytes(4, "big", signed=True),
            _i16(self.temp_cdeg, "temp_cdeg").to_bytes(2, "big", signed=True),
            _u16(self.voltage_mv, "voltage_mv").to_bytes(2, "big"),
            _u8(self.gps_fix_quality, "gps_fix_quality").to_bytes(1, "big"),
            _i16(self.roll_cdeg, "roll_cdeg").to_bytes(2, "big", signed=True),
            _i16(self.pitch_cdeg, "pitch_cdeg").to_bytes(2, "big", signed=True),
            _i16(self.yaw_cdeg, "yaw_cdeg").to_bytes(2, "big", signed=True),
        ))

    @classmethod
    def decode(cls, payload: bytes) -> "FlightTelemetry":
        _require_len(payload, 40, "FC_COORD FLIGHT_TELEMETRY")
        return cls(
            time_ms=int.from_bytes(payload[0:4], "big"),
            stage=payload[4],
            accel_x_mg=int.from_bytes(payload[5:7], "big", signed=True),
            accel_y_mg=int.from_bytes(payload[7:9], "big", signed=True),
            accel_z_mg=int.from_bytes(payload[9:11], "big", signed=True),
            vel_x_cms=int.from_bytes(payload[11:13], "big", signed=True),
            vel_y_cms=int.from_bytes(payload[13:15], "big", signed=True),
            vel_z_cms=int.from_bytes(payload[15:17], "big", signed=True),
            lat_e7=int.from_bytes(payload[17:21], "big", signed=True),
            lon_e7=int.from_bytes(payload[21:25], "big", signed=True),
            alt_cm=int.from_bytes(payload[25:29], "big", signed=True),
            temp_cdeg=int.from_bytes(payload[29:31], "big", signed=True),
            voltage_mv=int.from_bytes(payload[31:33], "big"),
            gps_fix_quality=payload[33],
            roll_cdeg=int.from_bytes(payload[34:36], "big", signed=True),
            pitch_cdeg=int.from_bytes(payload[36:38], "big", signed=True),
            yaw_cdeg=int.from_bytes(payload[38:40], "big", signed=True),
        )


@dataclass(frozen=True)
class AirbrakeTelemetry:
    time_ms: int
    stage: int
    accel_x_mg: int
    accel_y_mg: int
    accel_z_mg: int
    vel_x_cms: int
    vel_y_cms: int
    vel_z_cms: int
    temp_cdeg: int
    voltage_mv: int
    roll_cdeg: int
    pitch_cdeg: int
    yaw_cdeg: int
    airbrake_angle_cdeg: int
    predicted_apogee_cm: int
    original_apogee_estimate_cm: int
    blueraven_alt_cm: int

    def encode(self) -> bytes:
        return b"".join((
            _u32(self.time_ms, "time_ms").to_bytes(4, "big"),
            _u8(self.stage, "stage").to_bytes(1, "big"),
            _i16(self.accel_x_mg, "accel_x_mg").to_bytes(2, "big", signed=True),
            _i16(self.accel_y_mg, "accel_y_mg").to_bytes(2, "big", signed=True),
            _i16(self.accel_z_mg, "accel_z_mg").to_bytes(2, "big", signed=True),
            _i16(self.vel_x_cms, "vel_x_cms").to_bytes(2, "big", signed=True),
            _i16(self.vel_y_cms, "vel_y_cms").to_bytes(2, "big", signed=True),
            _i16(self.vel_z_cms, "vel_z_cms").to_bytes(2, "big", signed=True),
            _i16(self.temp_cdeg, "temp_cdeg").to_bytes(2, "big", signed=True),
            _u16(self.voltage_mv, "voltage_mv").to_bytes(2, "big"),
            _i16(self.roll_cdeg, "roll_cdeg").to_bytes(2, "big", signed=True),
            _i16(self.pitch_cdeg, "pitch_cdeg").to_bytes(2, "big", signed=True),
            _i16(self.yaw_cdeg, "yaw_cdeg").to_bytes(2, "big", signed=True),
            _i16(self.airbrake_angle_cdeg, "airbrake_angle_cdeg").to_bytes(2, "big", signed=True),
            _i32(self.predicted_apogee_cm, "predicted_apogee_cm").to_bytes(4, "big", signed=True),
            _i32(self.original_apogee_estimate_cm, "original_apogee_estimate_cm").to_bytes(4, "big", signed=True),
            _i32(self.blueraven_alt_cm, "blueraven_alt_cm").to_bytes(4, "big", signed=True),
        ))

    @classmethod
    def decode(cls, payload: bytes) -> "AirbrakeTelemetry":
        _require_len(payload, 41, "FC_COORD AIRBRAKE_TELEMETRY")
        return cls(
            time_ms=int.from_bytes(payload[0:4], "big"),
            stage=payload[4],
            accel_x_mg=int.from_bytes(payload[5:7], "big", signed=True),
            accel_y_mg=int.from_bytes(payload[7:9], "big", signed=True),
            accel_z_mg=int.from_bytes(payload[9:11], "big", signed=True),
            vel_x_cms=int.from_bytes(payload[11:13], "big", signed=True),
            vel_y_cms=int.from_bytes(payload[13:15], "big", signed=True),
            vel_z_cms=int.from_bytes(payload[15:17], "big", signed=True),
            temp_cdeg=int.from_bytes(payload[17:19], "big", signed=True),
            voltage_mv=int.from_bytes(payload[19:21], "big"),
            roll_cdeg=int.from_bytes(payload[21:23], "big", signed=True),
            pitch_cdeg=int.from_bytes(payload[23:25], "big", signed=True),
            yaw_cdeg=int.from_bytes(payload[25:27], "big", signed=True),
            airbrake_angle_cdeg=int.from_bytes(payload[27:29], "big", signed=True),
            predicted_apogee_cm=int.from_bytes(payload[29:33], "big", signed=True),
            original_apogee_estimate_cm=int.from_bytes(payload[33:37], "big", signed=True),
            blueraven_alt_cm=int.from_bytes(payload[37:41], "big", signed=True),
        )


@dataclass(frozen=True)
class PayloadTelemetry:
    time_ms: int
    stage: int
    accel_x_mg: int
    accel_y_mg: int
    accel_z_mg: int
    vel_x_cms: int
    vel_y_cms: int
    vel_z_cms: int
    temp_cdeg: int
    voltage_mv: int
    roll_cdeg: int
    pitch_cdeg: int
    yaw_cdeg: int
    motor_x_um: int
    motor_y_um: int
    percent_complete: int

    def encode(self) -> bytes:
        return b"".join((
            _u32(self.time_ms, "time_ms").to_bytes(4, "big"),
            _u8(self.stage, "stage").to_bytes(1, "big"),
            _i16(self.accel_x_mg, "accel_x_mg").to_bytes(2, "big", signed=True),
            _i16(self.accel_y_mg, "accel_y_mg").to_bytes(2, "big", signed=True),
            _i16(self.accel_z_mg, "accel_z_mg").to_bytes(2, "big", signed=True),
            _i16(self.vel_x_cms, "vel_x_cms").to_bytes(2, "big", signed=True),
            _i16(self.vel_y_cms, "vel_y_cms").to_bytes(2, "big", signed=True),
            _i16(self.vel_z_cms, "vel_z_cms").to_bytes(2, "big", signed=True),
            _i16(self.temp_cdeg, "temp_cdeg").to_bytes(2, "big", signed=True),
            _u16(self.voltage_mv, "voltage_mv").to_bytes(2, "big"),
            _i16(self.roll_cdeg, "roll_cdeg").to_bytes(2, "big", signed=True),
            _i16(self.pitch_cdeg, "pitch_cdeg").to_bytes(2, "big", signed=True),
            _i16(self.yaw_cdeg, "yaw_cdeg").to_bytes(2, "big", signed=True),
            _i32(self.motor_x_um, "motor_x_um").to_bytes(4, "big", signed=True),
            _i32(self.motor_y_um, "motor_y_um").to_bytes(4, "big", signed=True),
            _u8(self.percent_complete, "percent_complete").to_bytes(1, "big"),
        ))

    @classmethod
    def decode(cls, payload: bytes) -> "PayloadTelemetry":
        _require_len(payload, 36, "FC_COORD PAYLOAD_TELEMETRY")
        return cls(
            time_ms=int.from_bytes(payload[0:4], "big"),
            stage=payload[4],
            accel_x_mg=int.from_bytes(payload[5:7], "big", signed=True),
            accel_y_mg=int.from_bytes(payload[7:9], "big", signed=True),
            accel_z_mg=int.from_bytes(payload[9:11], "big", signed=True),
            vel_x_cms=int.from_bytes(payload[11:13], "big", signed=True),
            vel_y_cms=int.from_bytes(payload[13:15], "big", signed=True),
            vel_z_cms=int.from_bytes(payload[15:17], "big", signed=True),
            temp_cdeg=int.from_bytes(payload[17:19], "big", signed=True),
            voltage_mv=int.from_bytes(payload[19:21], "big"),
            roll_cdeg=int.from_bytes(payload[21:23], "big", signed=True),
            pitch_cdeg=int.from_bytes(payload[23:25], "big", signed=True),
            yaw_cdeg=int.from_bytes(payload[25:27], "big", signed=True),
            motor_x_um=int.from_bytes(payload[27:31], "big", signed=True),
            motor_y_um=int.from_bytes(payload[31:35], "big", signed=True),
            percent_complete=payload[35],
        )


class RadioType(IntEnum):
    SET_FREQUENCY = 0x01
    SET_TX_POWER = 0x02
    GET_STATUS = 0x03
    SET_PHY_PROFILE = 0x04
    STATUS_REPORT = 0x10

RADIO_ERR_TX_BUSY = 0x01
RADIO_ERR_PLL_UNLOCK = 0x02
RADIO_ERR_OVERTEMP = 0x04
RADIO_ERR_RX_OVERRUN = 0x08
RADIO_PHY_PROFILE_SAFE_BW125 = 0x00
RADIO_PHY_PROFILE_FAST_BW500 = 0x01


@dataclass(frozen=True)
class RadioSetFrequency:
    frequency_hz: int

    def encode(self) -> bytes:
        return _u32(self.frequency_hz, "frequency_hz").to_bytes(4, "big")

    @classmethod
    def decode(cls, payload: bytes) -> "RadioSetFrequency":
        _require_len(payload, 4, "RADIO SET_FREQUENCY")
        return cls(frequency_hz=int.from_bytes(payload[0:4], "big"))


@dataclass(frozen=True)
class RadioSetTxPower:
    tx_power_dbm: int

    def encode(self) -> bytes:
        return _i8(self.tx_power_dbm, "tx_power_dbm").to_bytes(1, "big", signed=True)

    @classmethod
    def decode(cls, payload: bytes) -> "RadioSetTxPower":
        _require_len(payload, 1, "RADIO SET_TX_POWER")
        return cls(tx_power_dbm=int.from_bytes(payload[0:1], "big", signed=True))


@dataclass(frozen=True)
class RadioSetPhyProfile:
    profile_id: int

    def encode(self) -> bytes:
        return _u8(self.profile_id, "profile_id").to_bytes(1, "big")

    @classmethod
    def decode(cls, payload: bytes) -> "RadioSetPhyProfile":
        _require_len(payload, 1, "RADIO SET_PHY_PROFILE")
        return cls(profile_id=payload[0])


@dataclass(frozen=True)
class RadioStatusReport:
    frequency_hz: int
    tx_power_dbm: int
    rssi_dbm: int
    snr_db: int
    error_flags: int
    packets_rx: int
    packets_tx: int

    def encode(self) -> bytes:
        return b"".join((
            _u32(self.frequency_hz, "frequency_hz").to_bytes(4, "big"),
            _i8(self.tx_power_dbm, "tx_power_dbm").to_bytes(1, "big", signed=True),
            _i8(self.rssi_dbm, "rssi_dbm").to_bytes(1, "big", signed=True),
            _i8(self.snr_db, "snr_db").to_bytes(1, "big", signed=True),
            _u8(self.error_flags, "error_flags").to_bytes(1, "big"),
            _u16(self.packets_rx, "packets_rx").to_bytes(2, "big"),
            _u16(self.packets_tx, "packets_tx").to_bytes(2, "big"),
        ))

    @classmethod
    def decode(cls, payload: bytes) -> "RadioStatusReport":
        _require_len(payload, 12, "RADIO STATUS_REPORT")
        return cls(
            frequency_hz=int.from_bytes(payload[0:4], "big"),
            tx_power_dbm=int.from_bytes(payload[4:5], "big", signed=True),
            rssi_dbm=int.from_bytes(payload[5:6], "big", signed=True),
            snr_db=int.from_bytes(payload[6:7], "big", signed=True),
            error_flags=payload[7],
            packets_rx=int.from_bytes(payload[8:10], "big"),
            packets_tx=int.from_bytes(payload[10:12], "big"),
        )


def decode_netmgmt(type: int, payload: bytes) -> object | None:
    msg_type = NetMgmtType(type)
    if msg_type is NetMgmtType.ACK:
        return Ack.decode(payload)
    _require_empty(payload, msg_type.name)
    return None


def decode_fc_coord(type: int, payload: bytes) -> object | None:
    msg_type = FcCoordType(type)
    if msg_type is FcCoordType.FLIGHT_TELEMETRY:
        return FlightTelemetry.decode(payload)
    if msg_type is FcCoordType.AIRBRAKE_TELEMETRY:
        return AirbrakeTelemetry.decode(payload)
    if msg_type is FcCoordType.PAYLOAD_TELEMETRY:
        return PayloadTelemetry.decode(payload)
    _require_empty(payload, msg_type.name)
    return None


def decode_radio(type: int, payload: bytes) -> object | None:
    msg_type = RadioType(type)
    if msg_type is RadioType.SET_FREQUENCY:
        return RadioSetFrequency.decode(payload)
    if msg_type is RadioType.SET_TX_POWER:
        return RadioSetTxPower.decode(payload)
    if msg_type is RadioType.SET_PHY_PROFILE:
        return RadioSetPhyProfile.decode(payload)
    if msg_type is RadioType.STATUS_REPORT:
        return RadioStatusReport.decode(payload)
    _require_empty(payload, msg_type.name)
    return None


def _require_len(payload: bytes, expected: int, name: str) -> None:
    if len(payload) != expected:
        raise MessageError(f"{name} payload must be {expected} bytes")


def _require_empty(payload: bytes, name: str) -> None:
    if payload:
        raise MessageError(f"{name} payload must be empty")


def _u8(value: int, name: str) -> int:
    if not 0 <= value <= 255:
        raise MessageError(f"{name} must fit in one byte")
    return value

def _i8(value: int, name: str) -> int:
    if not -128 <= value <= 127:
        raise MessageError(f"{name} must fit in signed one byte")
    return value

def _i16(value: int, name: str) -> int:
    if not -32768 <= value <= 32767:
        raise MessageError(f"{name} must fit in signed two bytes")
    return value

def _u16(value: int, name: str) -> int:
    if not 0 <= value <= 65535:
        raise MessageError(f"{name} must fit in two bytes")
    return value

def _i32(value: int, name: str) -> int:
    if not -2147483648 <= value <= 2147483647:
        raise MessageError(f"{name} must fit in signed four bytes")
    return value

def _u32(value: int, name: str) -> int:
    if not 0 <= value <= 4294967295:
        raise MessageError(f"{name} must fit in four bytes")
    return value
